baseURL: 'https://ubuntu-uk.org'
languageCode: en-gb
title: 'Ubuntu UK Community'
theme: "ubuntukr"
buildFuture: true
#googleAnalytics: ""
params:
  contact: admin@ubuntu-uk.org
  github: ubuntu-uk
  launchpad: ubuntu-uk
  mastodon: https://floss.social/@ubuntu_UK
  source_repo: https://github.com/ubuntu-uk/ubuntu-uk.github.io
defaultContentLanguage: en
languages:
  en:
    languageName: English
    title: Ubuntu UK Community
    weight: 2
    params:
      description: >-
        Ubuntu UK Community is a Ubuntu LoCo (Local Community) in the UK. 
        It is a place for everyone who is interested in using, developing with Ubuntu, or contributing to Ubuntu projects.
      copyright: >-
        Original template © 2021 Ubuntu Korean LoCo Team.
        © 2024 Ubuntu UK LoCo Team.
        Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY-SA 4.0. 
        Ubuntu and Canonical are registered trademarks of Canonical Ltd.
      main_slide:
        label: About the community
        link: about
    menu:
      main:
      - identifier: try
        name: Try Ubuntu
        weight: 1
      - identifier: download
        parent: try
        name: Download
        url: download
        weight: 20
      - identifier: hardware
        name: Ubuntu Certified Hardware
        parent: try
        url: https://ubuntu.com/certified
        weight: 20
      - identifier: docs-en
        parent: try
        name: Docs
        url: https://docs.ubuntu.com
        weight: 22
      - identifier: tutorials-en
        parent: try
        name: Tutorials
        url: https://ubuntu.com/tutorials
        weight: 23
      - identifier: wiki-en
        parent: try
        name: Wiki
        url: https://wiki.ubuntu.com
        weight: 24
      - identifier: about-group
        name: About
        weight: 2
      # - identifier: about
      #   parent: about-group
      #   name: About our community
      #   url: about
      #   weight: 24
      - identifier: community
        name: Community
        url: community
        weight: 3
      - identifier: forum
        parent: community
        name: Forum (Discourse)
        url: https://discourse.ubuntu.com/c/locos/ubuntu-uk
        weight: 32
      - identifier: lists
        parent: community
        name: Mailing list
        url: https://lists.ubuntu.com/archives/ubuntu-uk/
        weight: 35
      - identifier: chat
        parent: community
        name: Chat 
        url: chat
        weight: 36
      - identifier: follow
        name: Follow us
        weight: 5
      - identifier: mastodon
        parent: follow
        name: Mastodon
        url: https://floss.social/@ubuntu_UK
        weight: 4
